CREATE DATABASE IF NOT EXISTS ocr;

USE ocr;

CREATE TABLE IF NOT EXISTS ocr_record (
    id INT PRIMARY KEY AUTO_INCREMENT,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(10),
    ocr_result JSON
);
